### PR TITLE
changed stdc++fs to libc++

### LINKED ISSUE #52: Allow to use libc++ in CMake builds
The filesystem library is hardcoded as the libstdc++ one:
```
set(FILESYSTEM_LIB_NAME stdc++fs)
```

### PR DESCRIPTION
**Pull request by Forchapeatl**
fixed #52

### CODE REVIEW

**Comment by kuhar** [comment]
Closing due to no activity in 3+ weeks.

**Comment by Forchapeatl** [comment]
Hello kuhar, I noticed this PR was not merged. Please could you tell me the issues with this PR. I will fix it up.

**Comment by kuhar** [comment]
> Hello kuhar, I noticed this PR was not merged. Please could you tell me the issues with this PR. I will fix it up.

We require contributors to sign the CLA. See the comment made by the bot.

**Comment by Forchapeatl** [comment]
Thank you, Please have a look here [https://github.com/google/vulkan-performance-layers/pull/101/checks](https://github.com/google/vulkan-performance-layers/pull/101/checks) . I just signed it

**Comment by kuhar** [comment]
> Thank you, Please have a look here https://github.com/google/vulkan-performance-layers/pull/101/checks . I just signed it

Thanks. I looked at the change and see a couple few issues:
1. The change is stale now and needs to be rebased.
2. We don't want to switch from libstdc++ to libc++ everywhere. Instead, we should detect when libstdc++ is used and only then link with the filesystem library for libstdc++.

**Comment by Forchapeatl** [comment]
>We don't want to switch from libstdc++ to libc++ everywhere. Instead, we should detect when libstdc++ is used and only then link with the filesystem library for libstdc++.

 Please did you mean 
we should detect when `libstdc++` is used and only then link with the filesystem library for `libc++` ?

**Comment by kuhar** [comment]
We should check if libstdc++ is being used and if yest, link with the filesystem library for libstdc++

**Comment by Forchapeatl** [comment]
> We should check if libstdc++ is being used and if yest, link with the filesystem library for libstdc++

Hello @kuhar , sorry it took a while, I am still trying to get around CMake. Please is this the right approach ?
```c++
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")  
    set(FILESYSTEM_LIB_NAME stdc++fs)
```

**Review by rexionmars — APPROVED** [review]

**Comment by kuhar** [comment]
This PR does not seem to be moving forward. Closing so that it does not get mistaken as 'approved'.

**Pull request closed without merging**
